/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

/**
 *
 * @author Adrien
 */
public class ApplicationADataMining extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationADataMining
     */
    public ApplicationADataMining() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStatistiqueDescriptive = new javax.swing.JButton();
        jButtonExplorationDonnees = new javax.swing.JButton();
        jButtonAnalyseDonnees = new javax.swing.JButton();
        jButtonEchantillonnage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonStatistiqueDescriptive.setText("Statistique descriptive");
        jButtonStatistiqueDescriptive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatistiqueDescriptiveActionPerformed(evt);
            }
        });

        jButtonExplorationDonnees.setText("Exploration des données");
        jButtonExplorationDonnees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExplorationDonneesActionPerformed(evt);
            }
        });

        jButtonAnalyseDonnees.setText("Analyse des données");
        jButtonAnalyseDonnees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalyseDonneesActionPerformed(evt);
            }
        });

        jButtonEchantillonnage.setText("Echantillonnage");
        jButtonEchantillonnage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEchantillonnageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStatistiqueDescriptive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExplorationDonnees, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jButtonAnalyseDonnees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEchantillonnage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStatistiqueDescriptive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExplorationDonnees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnalyseDonnees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEchantillonnage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStatistiqueDescriptiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatistiqueDescriptiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStatistiqueDescriptiveActionPerformed

    private void jButtonExplorationDonneesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExplorationDonneesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExplorationDonneesActionPerformed

    private void jButtonAnalyseDonneesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalyseDonneesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnalyseDonneesActionPerformed

    private void jButtonEchantillonnageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEchantillonnageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEchantillonnageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationADataMining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationADataMining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationADataMining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationADataMining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationADataMining().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalyseDonnees;
    private javax.swing.JButton jButtonEchantillonnage;
    private javax.swing.JButton jButtonExplorationDonnees;
    private javax.swing.JButton jButtonStatistiqueDescriptive;
    // End of variables declaration//GEN-END:variables
}
